const mongoose = require("mongoose");

// One document per calendar day (dateKey = "YYYY-MM-DD"), generated by the
// daily cron job in services/cron/dailyJobs.js. Upserted, so re-running the
// job the same day (e.g. via the manual "run now" endpoint) just refreshes it
// instead of creating duplicates.
const DailyContentSchema = new mongoose.Schema(
  {
    dateKey: { type: String, required: true, unique: true }, // "2026-07-28"
    learningTopic: {
      title: { type: String, default: "" },
      summary: { type: String, default: "" },
      category: { type: String, default: "" },
    },
    quiz: [
      {
        question: String,
        options: [String],
        correctIndex: Number,
        explanation: String,
      },
    ],
  },
  { timestamps: true }
);

module.exports = mongoose.model("DailyContent", DailyContentSchema);
